/* USER */
export const LOGIN_USER = "LOGIN_USER";

/* JOBS */
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";
export const CLEAR_USER_JOB_FILTER_SELECTIONS =
  "CLEAR_USER_JOB_FILTER_SELECTIONS";

/* ORGANIZATIONS */
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

/* JOB TYPES */
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

/* DEGREES */
export const RECEIVE_DEGREES = "RECEIVE_DEGREES";
export const FETCH_DEGREES = "FETCH_DEGREES";
export const UNIQUE_DEGREES = "UNIQUE_DEGREES";
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE";
export const ADD_SELECTED_DEGREES = "ADD_SELECTED_DEGREES";

/*SKILLS AND QUALIFICATIONS*/
export const UPDATE_SKILLS_SEARCH_TERM = "UPDATE_SKILLS_SEARCH_TERM";
export const INCLUDE_JOB_BY_SKILL = "INCLUDE_JOB_BY_SKILL";

/*LOCATION*/
export const UPDATE_LOCATION_SEARCH_TERM = "UPDATE_LOCATION_SEARCH_TERM";
export const INCLUDE_JOB_BY_LOCATION = "INCLUDE_JOB_BY_LOCATION";

/*TEAMS*/
export const FILTERED_TEAMS = "FILTERED_TEAMS";
export const FETCH_TEAMS = "FETCH_TEAMS";
export const RECEIVE_TEAMS = "RECEIVE_TEAMS";
export const UNIQUE_LOCATIONS = "UNIQUE_LOCATIONS";
export const UNIQUE_QUALIFICATIONS = "UNIQUE_QUALIFICATIONS";
export const UNIQUE_LANGUAGES = "UNIQUE_LANGUAGES";
export const UNIQUE_PERIODS = "UNIQUE_PERIODS";
export const UNIQUE_PATENTA = "UNIQUE_PATENTA";
export const UNIQUE_CAR = "UNIQUE_CAR";
export const ADD_SELECTED_LOCATIONS = "ADD_SELECTED_LOCATIONS";
export const ADD_SELECTED_QUALIFICATIONS = "ADD_SELECTED_QUALIFICATIONS";
export const ADD_SELECTED_TEAM_LANGUAGES = "ADD_SELECTED_TEAM_LANGUAGES";
export const ADD_SELECTED_PATENTA = "ADD_SELECTED_PATENTA";
export const ADD_SELECTED_CAR = "ADD_SELECTED_CAR";
export const CLEAR_USER_TEAM_FILTER_SELECTIONS =
  "CLEAR_USER_TEAM_FILTER_SELECTIONS";
export const UPDATE_NAME_SEARCH_TERM = "UPDATE_NAME_SEARCH_TERM";
export const UPDATE_JOB_SEARCH_TERM = "UPDATE_JOB_SEARCH_TERM";
export const UPDATE_PERIOD_SEARCH_TERM = "UPDATE_PERIOD_SEARCH_TERM";

/* INCLUDES */
export const INCLUDE_TEAM_BY_LOCATION = "INCLUDE_TEAM_BY_LOCATION";
export const INCLUDE_TEAM_BY_QUALIFICATION = "INCLUDE_TEAM_BY_QUALIFICATION";
export const INCLUDE_TEAM_BY_LANGUAGE = "INCLUDE_TEAM_BY_LANGUAGE";
export const INCLUDE_TEAM_BY_JOB = "INCLUDE_TEAM_BY_JOB";
export const INCLUDE_TEAM_BY_NAME = "INCLUDE_TEAM_BY_NAME";
export const INCLUDE_TEAM_BY_PATENTA = "INCLUDE_TEAM_BY_PATENTA";
export const INCLUDE_TEAM_BY_CAR = "INCLUDE_TEAM_BY_CAR";
export const INCLUDE_TEAM_BY_MACCHINA = "INCLUDE_TEAM_BY_MACCHINA";
export const INCLUDE_TEAM_BY_ADDRESS = "INCLUDE_TEAM_BY_ADDRESS";
export const INCLUDE_TEAM_BY_PERIOD = "INCLUDE_TEAM_BY_PERIOD";
