# Generated by Django 4.1.1 on 2022-09-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='car',
            field=models.CharField(max_length=300),
        ),
    ]
