# Generated by Django 4.1.1 on 2022-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_database', '0002_alter_teams_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='car',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teams',
            name='patenta',
            field=models.CharField(max_length=300),
        ),
    ]
